---
title: Privacy Policy
---

## Introduction

Our Privacy Policy complies with the standards required by the *Personal Information Protection and Electronic Documents Act (PIPEDA)*. We explain below how we collect, use and disclose the personal information you may provide to us while using our website ([www.ghement.ca](www.ghement.ca)) and our statistical consulting and training services.

## Your Consent

It is always your choice whether or not you wish to provide personal information to us. Any personal information you provide will be treated with utmost care, and subject to this Privacy Policy will not be used or disclosed in ways to which you have not consented.

## Collection and Disclosure of Personal Information

In order to provide you with our services, we may have to ask you to supply some personal information, such as your name, position, e-mail address, postal address, telephone number and fax number. We will use your personal information for the following purposes:

#. To contact and correspond with you regarding the services requested by you;
#. To bill you, invoice you or refund you for these services;
#. To otherwise provide to you these services;
#. To improve our general operations so that we can better serve you in the future.

We will not disclose, sell, trade, or rent your personal information to any outside parties.

## Internet Links

On our site, we have provided links to external sites that we think you may find useful. These sites may have different privacy policies and you should be aware of each site's privacy policy before providing any personal information to that site. We are not responsible or liable for any personal information you provide to external sites that we have linked to.

## How to Contact Us Regarding Privacy

If you have any questions or concerns about this Privacy Policy or would like to contact us regarding the personal information you have submitted to us, you can contact us at the following address:

**Ghement Statistical Consulting Company Ltd.**

- 301-7031 Blundell Road
- Richmond, B.C.
- Canada, V6Y 1J5
- Tel: 604-767-1250
- Fax: 604-270-3922
- E-mail: [info@ghement.ca](info@ghement.ca)
- Web: [www.ghement.ca](www.ghement.ca)

